const FeedData = [
  {
    online: "true",
    profilePic: require("../../../../../assets/smilingWoman.jpg"),
    userName: "Clara M.",
    time: "10min",
    IconName: "location-sharp",
    IconText: "local",
    text: "StarPoint Hotel just started serving White Cakes,Its the best so far!",
    postPic: require("../../../../../assets/restaurantpic.jpg"),
    comments: "32 comments",
  },
  {
    online: "true",
    profilePic: require("../../../../../assets/man1.jpg"),
    userName: "Tommy Lee",
    time: "30min",
    IconName: "navigate",
    IconText: "Arrival",
    text: "Am looking to move to this estate,any chess players around? am a pro! ;)",
    comments: "15 comments",
  },
  {
    profilePic: require("../../../../../assets/woman1.jpg"),
    userName: "Angela Smith",
    time: "45min",
    IconName: "location-sharp",
    IconText: "local",
    text: "Having fun at the culture festival,you'all should come its lit!!",
    postPic: require("../../../../../assets/culturefest.jpg"),
    comments: "50 comments",
  },
  {
    online: "true",
    profilePic: require("../../../../../assets/man2.jpg"),
    userName: "Mark Duke.",
    time: "1hr",
    IconName: "navigate",
    IconText: "Arrival",
    text: "When I visit this area, am looking to go to this park,is it safe to go hiking here at night? Are there wild animals?",
    postPic: require("../../../../../assets/parktrail.jpg"),
    comments: "120 comments",
  },
  {
    online: "true",
    profilePic: require("../../../../../assets/woman2.jpg"),
    userName: "Susan Drew.",
    time: "1hr",
    IconName: "location-sharp",
    IconText: "Local",
    text: "Anyone know if Mombasa Road is floaded due to the rains? am trying to avoid the traffic jam",
    comments: "12 comments",
  },
];

export default FeedData;
